<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Report</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>

<body>
    @include('nav')
    <div class="container mt-4">

        @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
        @endif

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <h1>Generate Payment Report</h1>

        <form action="{{ route('payment-reports') }}" method="POST" class="mb-4">
            @csrf
            <div class="mb-3">
                <label for="year" class="form-label">Select Year</label>
                <select name="year" id="year" class="form-select" required>
                    <option value="">Choose Year</option>
                    @foreach ($years as $year)
                    <option value="{{ $year }}">{{ $year }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-3">
                <label for="month" class="form-label">Select Month</label>
                <select name="month" id="month" class="form-select" required>
                    <option value="">Choose Month</option>
                    @for ($i = 1; $i <= 12; $i++) <option value="{{ $i }}">{{ date('F', mktime(0, 0, 0, $i, 1)) }}
                        </option>
                        @endfor
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Generate Report</button>
        </form>

        @if ($totalPaid || $totalUnpaid)
        <h2>Report for {{ request('month') ? date('F', mktime(0, 0, 0, request('month'), 1)) : 'N/A' }}, Year {{
            request('year') }}</h2>
        <table class="table table-bordered mt-3">
            <thead>
                <tr>
                    <th>Total Paid</th>
                    <th>Total Unpaid</th>
                    <th>Total Amount</th>
                    <th>Percentage Amount Paid</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ number_format($totalPaid, 2) }}</td>
                    <td>{{ number_format($totalUnpaid, 2) }}</td>
                    <td>{{ number_format($totalFees, 2) }}</td>
                    <td>{{ number_format($percentagePaid, 2) }}%</td>
                </tr>
            </tbody>
        </table>

        <!-- Save Report Button -->
        <form action="{{ route('payment-reports.save') }}" method="POST">
            @csrf
            <input type="hidden" name="totalPaid" value="{{ $totalPaid }}">
            <input type="hidden" name="totalUnpaid" value="{{ $totalUnpaid }}">
            <input type="hidden" name="percentPaid" value="{{ $percentagePaid }}">
            <input type="hidden" name="totalAmount" value="{{ $totalFees }}">
            <input type="hidden" name="year" value="{{ request('year') }}">
            <input type="hidden" name="month" value="{{ date('F', mktime(0, 0, 0, request('month'), 1)) }}">
            <button type="submit" class="btn btn-success mt-3">Save Report</button>
        </form>
        @else
        <div class="alert alert-info">No payments found for the selected month and year.</div>
        @endif

        <!-- Section to display all generated reports -->
        <h2 class="mt-5">Generated Reports</h2>
        <table class="table table-bordered table-striped mt-3">
            <thead>
                <tr>
                    <th>Report ID</th>
                    <th>Generated By</th>
                    <th>Total Paid</th>
                    <th>Total Unpaid</th>
                    <th>Total Amount</th>
                    <th>Percentage Amount Paid</th>
                    <th>Year</th>
                    <th>Month</th>
                    <th>Created At</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($reports as $report)
                <tr>
                    <td>{{ $report->reportID }}</td>
                    <td>{{ $report->generatedBy }}</td>
                    <td>{{ number_format($report->totalPaid, 2) }}</td>
                    <td>{{ number_format($report->totalUnpaid, 2) }}</td>
                    <td>{{ number_format($report->totalAmount, 2) }}</td>
                    <td>{{ number_format($report->percentPaid, 2) }}%</td>
                    <td>{{ $report->Year }}</td>
                    <td>{{ $report->forMonth }}</td>
                    <td>{{ $report->created_at->format('d-m-Y H:i') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>


</body>

</html>